using System;

[Serializable]
public enum Items
{
    Cash = 1,
    Gold = 2,
    Armor_Points = 3,
    Knife_Points = 4,
    Pistol_Points = 5,
    Rifle_Points = 6,
    Shotgun_Points = 7,
    SMG_Points = 8,
    Sniper_Points = 9,
    Glasses = 10,
    Cap = 11,
    Helmet = 12,
    Bayonet_Easter_Time = 13,
    Bayonet_Summer_Vice = 14,
    M26 = 15,
    M67 = 16,
    Neurostim = 17,
    Regenerator = 18,
    Molotov = 19,
    Tier_1_Shotgun = 20,
    Tier_2_Mle = 21,
    Tier_2_Rifle = 22,
    Tier_3_Shotgun = 23,
    Tier_3_SMG = 24,
    Tier_3_Sniper = 25,
    Big_Case = 26,
    Bronze_Case = 27,
    Gold_Case = 28,
    Silver_Case = 29,
    Small_Case = 30,
    Standart_Case = 31,
    Super_Case = 32,
}